
# Configuration for Label Actions - https://github.com/dessant/label-actions

# The `Accepted` label is added to issues
Accepted:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Uncertain` label is added to issues
Uncertain:
  issues:
    # Remove labels
    unlabel:
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Bug` label is added to issues
Bug:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Cancelled` label is added to issues
Cancelled:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close and lock thread
    close: true
    # Add Comment
    comment: >
      Cancelled by/for: @{issue-author}

# The `Discussion` label is added to issues
Discussion:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Bug'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Enhancement'
      - 'Cannot-Replicate'

# The `Documentation` label is added to issues or pull requests
Documentation:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Duplicate` label is added to issues
Duplicate:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close and lock thread
    close: true
    # Add Comment
    comment: >
      Closed as a duplicate issue

# The `Enhancement` label is added to issues
Enhancement:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Tagged` label is added to issues
Tagged:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Queries'
      - 'Unclear'
      - 'Prorogued'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Good-First-Issue` label is added to issues
Good-First-Issue:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Help-Wanted` label is added to issues
Help-Wanted:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Incomplete` label is added to issues
Incomplete:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Duplicate'
      - 'Prorogued'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Invalid` label is added to issues
Invalid:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Queries'
      - 'Unclear'
      - 'Upstream'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Known-Issue` label is added to issues
Known-Issue:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Cannot-Replicate'
    # Close and lock thread
    close: true
    # Add Comment
    comment: >
      Closed as a known issue

# The `Parked` label is added to issues
Parked:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Stale'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Upstream` label is added to issues
Upstream:
  issues:
    # Add labels
    label:
      - 'Known-Issue'
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Stale'
      - 'Tagged'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Queries` label is added to issues
Queries:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Tagged'
      - 'Stale'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
  issues:
    # Reopen and unlock issue
    reopen: true

# The `Resolved` label is added to issues
Resolved:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close thread
    close: true

# The `Resolved` label is removed from issues
-Resolved:
  issues:
    # Reopen and unlock issue
    reopen: true
    unlock: true

# The `Stale` label is added to issues
Stale:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Tagged'
      - 'Queries'
      - 'Unclear'
      - 'Prorogued'
      - 'Duplicate'

# The `Unclear` label is added to issues
Unclear:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'

# The `Not-Planned` label is added to issues
Not-Planned:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Parked'
      - 'Stale'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
      - 'Cannot-Replicate'
    # Close and lock thread
    close: true
    # Add Comment
    comment: >
      Closed as not planned

# The `Not-Planned` label is removed from issues
-Not-Planned:
  issues:
    # Reopen and unlock issue
    reopen: true
    unlock: true

# The `Cannot-Replicate` label is added to issues
Cannot-Replicate:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Prorogued'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
    # Close and lock thread
    close: true
    # Add Comment
    comment: >
      Closed as unable to replicate the issue

# The `Prorogued` label is added to issues
Prorogued:
  issues:
    # Remove labels
    unlabel:
      - 'Uncertain'
      - 'Cancelled'
      - 'Accepted'
      - 'Resolved'
      - 'Triage'
      - 'Not-Planned'
      - 'Parked'
      - 'Stale'
      - 'Queries'
      - 'Unclear'
      - 'Invalid'
      - 'Duplicate'
      - 'Incomplete'
      - 'Known-Issue'
      - 'Cannot-Replicate'
    # Close thread
    close: true

# The `Prorogued` label is removed from issues
-Prorogued:
  issues:
    # Reopen and unlock issue
    reopen: true
    unlock: true
