name: 'Manage Issues'

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Job ID'
        required: true
        default: 'all'
  schedule:
    - cron: '4 4 */4 * *'

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Handle Stale Threads - https://github.com/actions/stale
  stale:
    name: Flag or Close Issues
    runs-on: ubuntu-latest

    if: github.event_name == 'schedule' || github.event.inputs.job_id == 'all' || github.event.inputs.job_id == 'stale'
    steps:

      - name: Close Resolved Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: ''
          close-issue-message: ''
          days-before-stale: 0
          days-before-close: 0
          exempt-assignees: ''
          stale-issue-label: 'Tagged'
          any-of-labels: 'Resolved'

      - name: Flag or Close Incomplete Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to missing required information.
          close-issue-message: >
            This item is being closed due to missing required information.
          days-before-stale: 0
          days-before-close: 3
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          remove-issue-stale-when-updated: true
          any-of-labels: 'Incomplete, Unclear'

      - name: Flag or Close No-Response Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to a lack of response.
          close-issue-message: >
            This item is being closed due to a lack of response.
          days-before-stale: 3
          days-before-close: 5
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          remove-issue-stale-when-updated: true
          any-of-labels: 'Queries'

      - name: Flag or Close Inactive Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to inactivity.
          close-issue-message: >
            This item is being closed due to inactivity.
          days-before-stale: 20
          days-before-close: 8
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          remove-issue-stale-when-updated: true
          exempt-issue-labels: 'Parked, Help-Wanted'

      - name: Flag or Close Parked Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to inactivity.
          close-issue-message: >
            This item is being closed due to inactivity.
          days-before-stale: 60
          days-before-close: 28
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          remove-issue-stale-when-updated: true
          any-of-labels: 'Parked'

      - name: Flag or Close Parked Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            This item has been flagged for closure due to inactivity.
          close-issue-message: >
            This item is being closed due to inactivity.
          days-before-stale: 120
          days-before-close: 60
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          remove-issue-stale-when-updated: true
          any-of-labels: 'Help-Wanted'

      - name: Close Duplicate Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item is being closed as a known issue.
          days-before-stale: 0
          days-before-close: 0
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'Duplicate, Known-Issue'

      - name: Close Invalid Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item is being closed as an invalid item.
          days-before-stale: 0
          days-before-close: 0
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'Invalid'

      - name: Close Wierd Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item is being closed as the issue could not be replicated.
          days-before-stale: 0
          days-before-close: 0
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'Cannot-Replicate'

      - name: Close WontFix Issues
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item is being closed as a fix will not be attempted.
          days-before-stale: 0
          days-before-close: 0
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'WontFix'

      - name: Catchall Closer
        uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ github.token }}
          close-issue-message: >
            This item is being closed as abandoned.
          days-before-stale: 180
          days-before-close: 180
          stale-issue-label: 'Tagged'

  # Lock Threads - https://github.com/dessant/lock-threads
  lock:
    name: Lock Threads
    needs: stale
    runs-on: ubuntu-latest

    if: github.event_name == 'schedule' || github.event.inputs.job_id == 'all' || github.event.inputs.job_id == 'lock'
    steps:

      - name: Lock Incomplete Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '2'
          include-any-issue-labels: 'Incomplete, Unclear'
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'

      - name: Lock Duplicate Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '2'
          include-any-issue-labels: 'Duplicate, Known-Issue'
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'

      - name: Lock WontFix Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          issue-inactive-days: '2'
          include-any-issue-labels: 'WontFix'
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'

      - name: Lock Invalid Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '2'
          include-any-issue-labels: 'Invalid, Cannot-Replicate'
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'

      - name: Lock Resolved Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          issue-comment: >
            This thread is being locked. Please create a new item if the issue persists or use the [Discussions](https://github.com/dakanji/RefindPlus/discussions) feature to discuss related issues.
          issue-inactive-days: '2'
          include-any-issue-labels: 'Resolved'
          exclude-any-issue-labels: 'Parked, Prorogued, Help-Wanted'
          add-issue-labels: ''
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'

      - name: Lock Inactive Issues
        uses: dessant/lock-threads@v3.0.0
        with:
          github-token: ${{ github.token }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '2'
          include-any-issue-labels: ''
          exclude-any-issue-labels: 'Parked, Prorogued, Help-Wanted'
          remove-issue-labels: 'Pending, Tagged, Queries'
          process-only: 'issues'
