name: 'Manage Issues'

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Job ID'
        required: true
        default: 'all'
  schedule:
    - cron: '5 5 */5 * *'

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Handle Stale Threads - https://github.com/actions/stale
  stale:
    name: Flag or Close Issues
    runs-on: ubuntu-20.04

    if: github.event_name == 'schedule' || github.event.inputs.job_id == 'all' || github.event.inputs.job_id == 'stale'
    steps:

      - name: Handle Cancelled/Duplicate/Invalid/Wierd/Not-Planned Issues
        uses: actions/stale@v7
        with:
          ignore-issue-updates: true
          close-issue-reason: 'completed'
          close-issue-message: ''
          days-before-stale: 0
          days-before-close: 1
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'Cancelled, Duplicate, Known-Issue, Invalid, Cannot-Replicate, Not-Planned'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Inter-Step-Pause
        run: |
          sleep 90s

      - name: Handle Incomplete Issues
        uses: actions/stale@v7
        with:
          close-issue-reason: 'completed'
          stale-issue-message: >
            This item is being flagged for closure due to missing required information.
          close-issue-message: >
            This item is being closed due to missing required information.
          days-before-stale: 0
          days-before-close: 3
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          remove-issue-stale-when-updated: true
          any-of-labels: 'Incomplete,'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Inter-Step-Pause
        run: |
          sleep 90s

      - name: Handle No-Response Issues
        uses: actions/stale@v7
        with:
          close-issue-reason: 'completed'
          stale-issue-message: |-
            Dear @${{ github.event.issue.user.login }},

            This item is being flagged for closure due to a lack of response.
          close-issue-message: |-
            Dear @${{ github.event.issue.user.login }},

            This item is being closed due to a lack of response.
          days-before-stale: 3
          days-before-close: 5
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          remove-issue-stale-when-updated: true
          any-of-labels: 'Queries'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Inter-Step-Pause
        run: |
          sleep 90s

      - name: Handle Resolved Issues
        uses: actions/stale@v7
        with:
          ignore-issue-updates: true
          close-issue-reason: 'completed'
          stale-issue-message: ''
          close-issue-message: ''
          days-before-stale: 0
          days-before-close: 1
          exempt-assignees: ''
          stale-issue-label: 'Tagged'
          any-of-labels: 'Resolved'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Inter-Step-Pause
        run: |
          sleep 90s

      - name: Catchall Closer
        uses: actions/stale@v7
        with:
          close-issue-reason: 'completed'
          stale-issue-message: >
            This item is being flagged for closure due to inactivity.
          close-issue-message: >
            This item is being closed due to inactivity.
          days-before-stale: 30
          days-before-close: 30
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          remove-issue-stale-when-updated: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Inter-Step-Pause
        run: |
          sleep 90s

  # Lock Threads - https://github.com/dakanji/lock-threads
  lock:
    name: Lock Threads
    needs: stale
    runs-on: ubuntu-20.04

    if: github.event_name == 'schedule' || github.event.inputs.job_id == 'all' || github.event.inputs.job_id == 'lock'
    steps:

      - name: Inter-Step-Pause
        run: |
          sleep 90s

      - name: Lock Declined Pull Requests
        uses: dakanji/lock-threads@v4.0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          issue-inactive-days: '0'
          include-any-issue-labels: 'Declined'
          remove-issue-labels: 'Tagged, Queries'
          process-only: 'prs'

      - name: Inter-Step-Pause
        run: |
          sleep 90s

      - name: Lock Not-Planned issues
        uses: dakanji/lock-threads@v4.0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          issue-inactive-days: '0'
          include-any-issue-labels: 'Not-Planned'
          remove-issue-labels: 'Triage, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            This thread is being locked.

            Please use the [Discussions Feature](https://github.com/dakanji/RefindPlus/discussions) for follow on discussion or raise a new issue if appropriate.
          process-only: 'issues'

      - name: Inter-Step-Pause
        run: |
          sleep 90s

      - name: Lock Invalid/Resolved Issues
        uses: dakanji/lock-threads@v4.0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          issue-inactive-days: '2'
          include-any-issue-labels: 'Invalid, Resolved'
          remove-issue-labels: 'Triage, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            This thread is being locked.

            Please use the [Discussions Feature](https://github.com/dakanji/RefindPlus/discussions) for follow on discussion or raise a new issue if appropriate.
          process-only: 'issues'

      - name: Inter-Step-Pause
        run: |
          sleep 90s

      - name: Lock Misc Issues
        uses: dakanji/lock-threads@v4.0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '2'
          include-any-issue-labels: 'Duplicate, Cannot-Replicate, Known-Issue, Cancelled'
          remove-issue-labels: 'Triage, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            This thread is being locked.

            Please use the [Discussions Feature](https://github.com/dakanji/RefindPlus/discussions) for follow on discussion or raise a new issue if appropriate.
          process-only: 'issues'

      - name: Inter-Step-Pause
        run: |
          sleep 90s

      - name: Lock Incomplete/Abandoned Issues
        uses: dakanji/lock-threads@v4.0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          add-issue-labels: 'Abandoned'
          issue-inactive-days: '5'
          include-any-issue-labels: 'Stale, Incomplete'
          remove-issue-labels: 'Triage, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            Dear @${{ github.event.issue.user.login }},

            This thread is being locked as it appears to have abandoned.
          process-only: 'issues'

      - name: Inter-Step-Pause
        run: |
          sleep 90s

      - name: Lock Unclear Issues
        uses: dakanji/lock-threads@v4.0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          issue-inactive-days: '7'
          include-any-issue-labels: 'Unclear'
          remove-issue-labels: 'Triage, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            This thread is being locked.

            Please use the [Discussions Feature](https://github.com/dakanji/RefindPlus/discussions) for follow on discussion or raise a new issue if appropriate.
          process-only: 'issues'

      - name: Inter-Step-Pause
        run: |
          sleep 90s

      - name: Lock Inactive Issues
        uses: dakanji/lock-threads@v4.0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '3'
          include-any-issue-labels: ''
          exclude-any-issue-labels: 'Unclear, Parked, Prorogued, Help-Wanted'
          remove-issue-labels: 'Triage, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            This thread is being locked.

            Please use the [Discussions Feature](https://github.com/dakanji/RefindPlus/discussions) for follow on discussion or raise a new issue if appropriate.
          process-only: 'issues'
