name: 'Manage Issues'

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Job ID'
        required: true
        default: 'all'
  schedule:
    - cron: '4 4 */4 * *'

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Handle Stale Threads - https://github.com/actions/stale
  stale:
    name: Flag or Close Issues
    runs-on: ubuntu-20.04

    if: github.event_name == 'schedule' || github.event.inputs.job_id == 'all' || github.event.inputs.job_id == 'stale'
    steps:

      - name: Handle Cancelled/Duplicate/Invalid/Wierd/Not-Planned Issues
        uses: actions/stale@v6
        with:
          close-issue-message: ''
          days-before-stale: 1
          days-before-close: 0
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'Cancelled, Duplicate, Known-Issue, Invalid, Cannot-Replicate, Not-Planned'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle Incomplete Issues
        uses: actions/stale@v6
        with:
          stale-issue-message: >
            This item is being flagged for closure due to missing required information.
          close-issue-message: >
            This item is being closed due to missing required information.
          days-before-stale: 0
          days-before-close: 3
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          remove-issue-stale-when-updated: true
          any-of-labels: 'Incomplete,'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle No-Response Issues
        uses: actions/stale@v6
        with:
          stale-issue-message: >
            This item is being flagged for closure due to a lack of response.
          close-issue-message: >
            This item is being closed due to a lack of response.
          days-before-stale: 3
          days-before-close: 5
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          remove-issue-stale-when-updated: true
          any-of-labels: 'Queries'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle Resolved Issues
        uses: actions/stale@v6
        with:
          stale-issue-message: ''
          close-issue-message: ''
          days-before-stale: 0
          days-before-close: 1
          exempt-assignees: ''
          stale-issue-label: 'Tagged'
          any-of-labels: 'Resolved'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Catchall Closer
        uses: actions/stale@v6
        with:
          stale-issue-message: >
            This item is being flagged for closure due to inactivity.
          close-issue-message: >
            This item is being closed due to inactivity.
          days-before-stale: 30
          days-before-close: 30
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          remove-issue-stale-when-updated: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  # Lock Threads - https://github.com/dessant/lock-threads
  lock:
    name: Lock Threads
    needs: stale
    runs-on: ubuntu-20.04

    if: github.event_name == 'schedule' || github.event.inputs.job_id == 'all' || github.event.inputs.job_id == 'lock'
    steps:

      - name: Lock Not-Planned issues
        uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          issue-inactive-days: '0'
          include-any-issue-labels: 'Not-Planned'
          remove-issue-labels: 'Not-Yet-Seen, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            This thread is being locked.

            Please use the [Discussions](https://github.com/dakanji/RefindPlus/discussions) feature for follow on discussion or raise a new issue if appropriate.
          process-only: 'issues'

      - name: Lock Invalid/Cancelled Issues
        uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          issue-inactive-days: '1'
          include-any-issue-labels: 'Invalid, Cancelled, Resolved'
          remove-issue-labels: 'Not-Yet-Seen, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            This thread is being locked.

            Please use the [Discussions](https://github.com/dakanji/RefindPlus/discussions) feature for follow on discussion or raise a new issue if appropriate.
          process-only: 'issues'

      - name: Lock Misc Issues
        uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '2'
          include-any-issue-labels: 'Duplicate, Cannot-Replicate, Known-Issue'
          remove-issue-labels: 'Not-Yet-Seen, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            This thread is being locked.

            Please use the [Discussions](https://github.com/dakanji/RefindPlus/discussions) feature for follow on discussion or raise a new issue if appropriate.
          process-only: 'issues'

      - name: Lock Incomplete/Abandoned Issues
        uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          add-issue-labels: 'Abandoned'
          issue-inactive-days: '5'
          include-any-issue-labels: 'Stale, Incomplete'
          remove-issue-labels: 'Not-Yet-Seen, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            This thread is being locked.

            Please use the [Discussions](https://github.com/dakanji/RefindPlus/discussions) feature for follow on discussion or raise a new issue if appropriate.
          process-only: 'issues'

      - name: Lock Unclear Issues
        uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          issue-inactive-days: '7'
          include-any-issue-labels: 'Unclear'
          remove-issue-labels: 'Not-Yet-Seen, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            This thread is being locked.

            Please use the [Discussions](https://github.com/dakanji/RefindPlus/discussions) feature for follow on discussion or raise a new issue if appropriate.
          process-only: 'issues'

      - name: Lock Inactive Issues
        uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-reason: ''
          add-issue-labels: 'Resolved'
          issue-inactive-days: '3'
          include-any-issue-labels: ''
          exclude-any-issue-labels: 'Unclear, Parked, Prorogued, Help-Wanted'
          remove-issue-labels: 'Not-Yet-Seen, Stale, Tagged, Queries, Uncertain'
          issue-comment: |-
            This thread is being locked.

            Please use the [Discussions](https://github.com/dakanji/RefindPlus/discussions) feature for follow on discussion or raise a new issue if appropriate.
          process-only: 'issues'
